version: 1.0.{build}
image: Visual Studio 2017
build_script:
- ps: .\build.ps1 -Target "Default"
#deploy:
#- provider: Environment
#  name: Swetugg Tix Lab ActivityJob
#- provider: Environment
#  name: Swetugg Tix Lab Web