version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017

build_script:
- ps: .\build.ps1 -Target "Default"

artifacts:
- path: .\dist\Swetugg.Tix.Web.zip
  type: Auto
- path: .\dist\Swetugg.Tix.Activity.Jobs.zip
  type: Auto
- path: .\dist\Swetugg.Tix.Ticket.Jobs.zip
  type: Auto
- path: .\dist\Swetugg.Tix.Process.Jobs.zip
  type: Auto

deploy:
- provider: Environment
  name: Swetugg Tix Latest