version: 1.0.{build}
image: Visual Studio 2017
build_script:
- ps: .\build.ps1 -Target "Default"

artifacts:
- path: .\dist\Swetugg.Tix.Web.zip
  type: WebDeployPackage
- path: .\dist\Swetugg.Tix.Activity.Jobs.zip
  type: WebDeployPackage

deploy:
- provider: Environment
  name: Swetugg Tix Latest