nuget:
  account_feed: true
  
install:
 - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
 - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
 - ps: dnvm update-self
 - ps: dnvm upgrade
 - ps: dnvm install 1.0.0-rc1-update1
 - ps: dnvm list
 - ps: dnvm use 1.0.0-rc1-update1
 - npm install -g gulp bower

before_build:
 - ps: dnu restore

build_script:
- dnu publish "src\Swetugg.Tix.Web" --out SwetuggTixWeb --configuration Release --runtime dnx-clr-win-x86.1.0.0-rc1-update1 --wwwroot-out "wwwroot" --quiet
- dnu publish "src\Swetugg.Tix.Activyt.Job" --out SwetuggTixActivityJob --configuration Release --runtime dnx-clr-win-x86.1.0.0-rc1-update1 --quiet

artifacts:
- path: SwetuggTixWeb
  name: SwetuggTixWeb
- path: SwetuggTixActivityJob
  name: SwetuggTixActivityJob
  
test_script:
- cmd: >-
    dnx -p test\Swetugg.Tix.Activity.Domain.Tests\project.json test

    dnx -p test\Swetugg.Tix.Ticket.Domain.Tests\project.json test

