@host = tix-dev-apia2add574.azurewebsites.net
#@host = http://localhost:7071
#@host = http://localhost:4711

@activityId = 7fedb79a-d174-41d3-93c6-f7f66257f648
@ticketTypeId = 41869799-3bd2-46ae-bae7-12c5783ce931
@commandId = 3fa37e91-286f-4f5c-aa00-4bafbd999145
@orderId = 8e6bf91e-e22a-40e9-9589-906506a7b298

### List all activities
GET {{host}}/api/activities

### Create a new Activity
POST {{host}}/api/activities 
Content-Type: application/json

{
  "name": "Test Activity 2"
}

### Get the status of a command
GET {{host}}/api/activities/commands/{{commandId}}


### Get the activity
GET {{host}}/api/activities/{{activityId}}

### Add available seats to an activity
POST {{host}}/api/activities/{{activityId}}/add-seats
Content-Type: application/json

{
  "seats": 10
}


### Remove available seats from an activity
POST {{host}}/api/activities/{{activityId}}/remove-seats
Content-Type: application/json

{
  "seats": 5
}

### Add a ticket type to an activity
POST {{host}}/api/activities/{{activityId}}/ticket-type

### Remove a ticket type from an activity
DELETE {{host}}/api/activities/{{activityId}}/ticket-types/{{ticketTypeId}}


### Get an order
GET {{host}}/api/orders/{{orderId}}

### Rebuild all views for an activity
POST {{host}}/api/activities-admin/{{activityId}}/rebuild

### Rebuild all views for an order
POST {{host}}/api/orders-admin/{{orderId}}/rebuild

### Rebuild all order views
POST {{host}}/api/orders-admin/rebuild

### Drop all tables from the View database
DELETE {{host}}/api/db-admin/views