@host = tix-dev-api46bff474.azurewebsites.net
#@host = http://localhost:7071
#@host = http://localhost:4711

@activityId = 989a8804-c77a-43a5-b910-8ba7dc7718a7
@ticketTypeId = 0ac4df30-0ba3-4c39-accc-4482009c808c
@commandId = 9933c6c3-d811-4b95-928c-d86bede6e94e
@orderId = 8e6bf91e-e22a-40e9-9589-906506a7b298

### List all activities
GET {{host}}/api/activities

### Create a new Activity
POST {{host}}/api/activities 
Content-Type: application/json

{
  "name": "Test Activity 2"
}

### Get the status of a command
GET {{host}}/api/activities/commands/{{commandId}}


### Get the activity
GET {{host}}/api/activities/{{activityId}}

### Add available seats to an activity
POST {{host}}/api/activities/{{activityId}}/add-seats
Content-Type: application/json

{
  "seats": 10
}


### Remove available seats from an activity
POST {{host}}/api/activities/{{activityId}}/remove-seats
Content-Type: application/json

{
  "seats": 5
}

### Add a ticket type to an activity
POST {{host}}/api/activities/{{activityId}}/ticket-types
Content-Type: application/json

{
  "name": "Early Birb"
}

### Remove a ticket type from an activity
DELETE {{host}}/api/activities/{{activityId}}/ticket-types/{{ticketTypeId}}


### Get an order
GET {{host}}/api/orders/{{orderId}}

### Rebuild all views for an activity
POST {{host}}/api/activities-admin/{{activityId}}/rebuild

### Rebuild all views for an order
POST {{host}}/api/orders-admin/{{orderId}}/rebuild

### Rebuild all order views
POST {{host}}/api/orders-admin/rebuild

### Drop all tables from the View database
DELETE {{host}}/api/db-admin/views